### PR TITLE
chore: publish cjs and esm

### PR DESCRIPTION
**Pull request by stramel**
Uses `@pika/pack` to publish and esm and cjs version.

/cc @fredkschott

### CODE REVIEW

**Comment by FredKSchott** [comment]
Bah, I've seen this `@pika/types` issue before. If you run `npm install` a second time, it should fix it in your existing package lock file. I need to figure out the root issue there.

**Comment by stramel** [comment]
@FredKSchott Seems like it only happens when `npm ci` command is ran.

**Comment by FredKSchott** [comment]
The root issue is that `@pika/types` isn't in your lockfile, so neither `ci` nor `install` will install it. Running `npm install` locally on an existing `package-lock.json`, and then committing that change has solved the issue for me in the past.

Edit: just tried quickly, and adding a second `npm install` step in travis should fix the issue as well. No idea why this is happening, I'll dig in asap.

**Comment by stramel** [comment]
Posted an issue on @pika/pack added some debugging info that is hopefully useful! https://github.com/pikapkg/pack/issues/23

**Comment by 43081j** [comment]
Closing this as replaced by #5.

Various reasons for not using pika in this particular case, DM me if you like and ill explain a little more (could be useful feedback for you especially fred).

**Pull request closed without merging**
